In [2]:
data_path = "./data/mnist_train.csv"
import numpy as np

In [3]:
train_data = np.genfromtxt(data_path, delimiter = ',', dtype=np.float)

In [4]:
train_data

array([[5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       ...,
       [5., 0., 0., ..., 0., 0., 0.],
       [6., 0., 0., ..., 0., 0., 0.],
       [8., 0., 0., ..., 0., 0., 0.]])

In [6]:
x_train = train_data[:, 1:]
y_train = train_data[:, 0]

In [7]:
x_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [9]:
y_train = (np.arange(10) == y_train[:, None]).astype(np.float32)
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [13]:
IMAGE_SIZE = 28
x_train = x_train.reshape(len(x_train), IMAGE_SIZE, IMAGE_SIZE, 1)
x_train.shape

(60000, 28, 28, 1)

In [1]:
import tensorflow as tf